# Results

```{r}
library(usmap)
library(ggplot2)

library(shiny)
library(r2d3)
library(tidyverse)
library(lubridate)
```

## Load Data
```{r}
covid19_merged_df =  read.csv("./data/Covid19_selected.csv")
covid19_merged_df$date = as.character(covid19_merged_df$date)
covid19_merged_df$date = parse_date(covid19_merged_df$date, format = "%Y-%m-%d")

US_cases_df$date = as.character(US_cases_df$date)
US_cases_df$date = parse_date(US_cases_df$date,format = "%Y-%m-%d")
```

## Compare death rates between two states in US (D3)
<script src="https://d3js.org/d3.v4.js"></script>
<b>Compare two states</b>
<select id="selectButton1"></select>
<select id="selectButton2"></select>
<div id="death_rate_plot"></div>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

```{r}
library(r2d3)

death_rate_df = covid19_merged_df %>%
  select(date, state, tot_cases, tot_death) %>%
  drop_na()

death_rate_df$death_rate = death_rate_df$tot_death / death_rate_df$tot_cases

US_cases_df$death_rate = US_cases_df$us_tot_death / US_cases_df$us_cases

r2d3(data=death_rate_df, script = "./js/death_rate.js")
```

## Total cases in US (static)
```{r}
# Extract total cases of each states by month
covid19_tot_cases = covid19_merged_df %>%
                    select(date, state, tot_cases) %>%
                    drop_na() %>%
                    mutate(Date_month = month(date)) %>%
                    group_by(Date_month, state) %>%
                    summarise(all_total = max(tot_cases))

covid19_tot_cases$Date_month = as.factor(covid19_tot_cases$Date_month)

# Plot the latest confirmed cases in US by states
plot_usmap(data = na.omit(covid19_tot_cases), values = "all_total", color = "red") + 
  scale_fill_continuous(name = "Confirmed",low = "white", high = "red") + 
  theme(legend.position = "right") +
  ggtitle("Confirmed covid-19 cases") +
  facet_wrap(~Date_month, ncol=3, drop=TRUE)
```

## Total cases in US (static statebins)
```{r}
library(statebins)
# Extract the fisrt and last month for all states
covid19_tot_cases = covid19_merged_df %>%
                    select(date, state, tot_cases) %>%
                    drop_na() %>%
                    mutate(Date_month = month(date))
covid19_tot_cases$state = as.character(covid19_tot_cases$state)

statebins(covid19_tot_cases, value_col="tot_cases",
          name = "Confirmed covid-19 cases", direction = 1) +
  ggtitle("Confirmed covid-19 cases") +
  theme_statebins() +
  facet_wrap(~Date_month, ncol=3, drop=TRUE)

```