# Conclusion

Using the data sources about COVID-19 cases in US and hospital capacity & COVID-19 patient impact, we gained interesting insights about the trend of pandemic in US, the relationships between hospital capacity and death rates of COVID-19, differences between the impact on adult & pediatric patients. Besides, the interactive plot by d3 enables us to compare the trend of death rates in different states and in US.  

The work we have done is only the first step to get the whole picture of the pandemic in US. The limitations and the future directions of our work are as follows:

* Although the trend of COVID-19 in US is clearly shown in the plots, we are still unknown about the factors that have effect on the situations. Given the COVID-19 cases & deat rates shown in all states of US, we are curious about the impact of the population size, economic situation, medical resources of different states on the change in the situation. Therefore, we would like to compare the conditions of some states suffering affect of different extent due to COVID-19.

* The relationships between the hospital capacity and death rates of COVID-19 inpire us about the importance of public medical resources. The spread-out of COVID-19 in US leads to insuffiency of patient beds and other resources in many states. To help control the pandemic in the states with high death rates and rapidly increasing new cases, we want to find out the differences between the health policies & rules of these states and others.

* In the plot of confirmed cases of adult & pediatric patients, the difference in the impact on both groups is not so evident since the numbers of cases in both groups are extremely imbalanced. Therefore, we are going to compare the growth rates and death rates in the two groups in the future. Besides, to get more insights about the impact of COVID-19 on people of different ages, we will find more data about the COVID-19 cases by age.

The plots in the report help us learn more about the trend of COVID-19 in US and its impact on the public by plotting the growth rates, death rates, hostipal capacity and etc. To study more about the pandemic in US, we need more statistical tools to find out the factors that are crucial to the break in COVID-19 cases in different states.