--- 
title: "USCovid19Analysis"
author: "Haoxiong Su; Jialu Xia; Yifei Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
```{r}
library(bookdown)
```

There is no doubt that the most popular topic in 2020 is covid-19. According to the data from NYTimes website, up to today, the total number of confirmed patients is about 17 millions (https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html). However, the development of Covid-19 in the United States is not monotonous, but there are many changes from March to December. Facing the unprecedented pandemic, as a student, what we need to do is to have a clear understanding of the current circumstances of covid-19 in our areas, to keep the updated development of covid-19, the effectiveness of Covid-19 protection policy in our locations. To achieve the above things, exploratory data analysis and visualization techniques can be leveraged. 

In our project, our team what to make use of those toolkits we learned during the 5702 EDAV courses, including tidyverse, ggplot2, d3, shiny, to conduct data analysis on the dataset about Covid-19, apart from giving audiences a general view of covid-19 in the United States, in each state, we also focus on the study of the situation of medical system (ICU, hospital beds), see the status of the medical system changes with the time pass and with the evalution of circumstance of covid-19. Apart from the analysis of the data itself, our project team also combine the pattern of data with the government policy and significant social events (stay at home order, shut down date, election day) to dive deeper into the root cause of the pattern.

Our project report can be a useful reference for readers to know better about the covid-19, know how the covid-19 have influenced our medical system, also know what policy, what approach is more helpful to control covid-19. We not only elaborate the data by visualization tools to make the data readable, but also leveraged interactive tool d3 to built an interactive dashboard to help readers have a better experience with our analysis results. 